language: python

python: 3.3

sudo: false

env:
  - TOXENV=py33,coveralls
  - TOXENV=py34,coveralls
  - TOXENV=check

matrix:
  allow_failures:
    - env: TOXENV=py33,coveralls
    - env: TOXENV=py34,coveralls
  fast_finish: true

install:
  - pip install tox

script:
  - tox
