language: python

sudo: false

python:
  - "3.3"
  - "3.4"

matrix:
  allow_failures:
    - python: "3.4"
  fast_finish: true

install:
  - "pip install flake8"
  - "pip install pydocstyle"
  - "pip install pytest-cov"
  - "pip install codecov"

before_script:
  - flake8 . --max-line-length=120 --exclude=__init__.py,linter-plugin-template,docs
  - pydocstyle . --add-ignore=D202

script:
  - py.test --cov .

after_success:
  - coverage xml
  - codecov
